package com.md.entity;// default package
// Generated 2015-12-5 12:46:46 by Hibernate Tools 3.4.0.CR1

import android.os.Parcel;
import android.os.Parcelable;

/**
 * UserValidate generated by hbm2java
 */
public class UserValidate implements Parcelable {

    private int userSecurityId;
    private String name;
    private String email;
    private String salt;
    private String password;

    public int getUserSecurityId() {
        return userSecurityId;
    }

    public void setUserSecurityId(int userSecurityId) {
        this.userSecurityId = userSecurityId;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeInt(this.userSecurityId);
        dest.writeString(this.name);
        dest.writeString(this.email);
        dest.writeString(this.salt);
        dest.writeString(this.password);
    }

    public UserValidate() {
    }

    protected UserValidate(Parcel in) {
        this.userSecurityId = in.readInt();
        this.name = in.readString();
        this.email = in.readString();
        this.salt = in.readString();
        this.password = in.readString();
    }

    public static final Parcelable.Creator<UserValidate> CREATOR = new Parcelable.Creator<UserValidate>() {
        public UserValidate createFromParcel(Parcel source) {
            return new UserValidate(source);
        }

        public UserValidate[] newArray(int size) {
            return new UserValidate[size];
        }
    };
}
